### ISSUE TITLE
FM4000 English handbook removed from circulation - request for copy.

### ISSUE THREAD

**Issue by burque505** [WollMux/WollMuxHandbuch#21]
Hallo, früher gab es ein [FormularMax Handbook in English](http://www.wollmux.net/files/FormularMax_Handbook_english.pdf). Dies is leider nicht mehr zu finden. Hat jemand eine Kopie davon? Ich wäre dafür aüsserst dankbar!

**Comment by smehrbrodt** [comment]
http://web.archive.org/web/20161020203633/http://www.wollmux.net/files/FormularMax_Handbook_english.pdf
