### ISSUE TITLE
wollmux.org doesn't show current page in URL

### ISSUE THREAD

**Issue by smehrbrodt** [WollMux/WollMuxHandbuch#5]
Open http://wollmux.org , then click on one of the menu items, e.g. "Eierlegender WollMux". Expected is that the URL changes. But instead wollmux.org is displayed as URL all the time.
That makes it impossible to share a link to a certain page.

Using https://wollmux.github.io/ this works as expected (clicking "Eierlegender WollMux" changes URL to https://wollmux.github.io/WollMuxHandbuch/Eierlegender_WollMux.html )

**Comment by sikelerd** [comment]
This issue is now resolved.

http://wollmux.github.io is no provided as http://wollmux.org
